
skillMetadata:
  sections:
    - name: AirGov Api Key. Note Only Valid In US, Request Key At (https://docs.airnowapi.org/account/request/)
      fields:
        - name: api_key
          type: text
          label: Api Key
          value: ""
          placeholder: "########-####-####-####-############"