
skillMetadata:
  sections:
    - name: Options << Name of section
      fields:
        - name: api_key
          type: text
          label: AirGov API Key. Note Only Valid In US, Request Key At (https://docs.airnowapi.org/account/request/)
          value: ""
          placeholder: "########-####-####-####-############"