
skillMetadata:
  sections:
    - name: Api Key
    - label: Request Key At <a href='https://aqicn.org/data-platform/token/#/'> The World Air Quality Index Project </a>
      fields:
        - name: api_key
          type: text
          label: Api Key
          value: None
          placeholder: "########-####-####-####-############"