
skillMetadata:
  sections:
    - name: Request Api Key At (https://docs.airnowapi.org/account/request/)
      fields:
        - name: api_key
          type: text
          label: Api Key
          value: ""
          placeholder: "########-####-####-####-############"